forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name='forum'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^create$',views.createPost, name='createPost'),
    url(r'^(?P<post_id>[0-9]+)$',views.viewpost, name='post'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$',views.logout, name='logout'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^forum/', include('forum.urls')),
]

forum/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    post_title=models.CharField(max_length=50)
    post_text=models.CharField(max_length=1000)
    post_author=models.CharField(max_length=30)
    post_pubdate=models.DateTimeField('date posted')
    def __str__(self):
        return self.post_text

class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text=models.CharField(max_length=50)
    comment_pubdate=models.DateTimeField('date commented')
    comment_author = models.CharField(max_length = 30)
    def __str__(self):
        return self.comment_text

home/models.py
from django.db import models

# Create your models here.
class User(models.Model):#Question table
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

forum/forms.py
from django import forms

class CreateComment(forms.Form):
    text = forms.CharField(label='Your comment',max_length=30)

class CreatePost(forms.Form):
    title = forms.CharField(label='Title: ', max_length = 50)
    content = forms.CharField(label = 'Content: ',max_length=1000)

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template.context_processors import csrf
from django.template import loader
from django.utils import timezone
from .models import Post, Comment
from .forms import CreateComment, CreatePost

# Create your views here.
def index(request):
    latest_post_list = Post.objects.order_by('-post_pubdate')
    template = loader.get_template('forum/forum.html')
    context ={
        'latest_post_list':latest_post_list,
    }
    return HttpResponse(template.render(context,request))

def viewpost(request, post_id):
    if request.method == 'POST':
        comment_form = CreateComment(request.POST)
        if comment_form.is_valid():
            # csrf_token = django.middleware.csrf.get_token(request)
            new_comment_text = comment_form.cleaned_data['text']
            new_comment = Comment(comment_post_id = post_id, comment_text=new_comment_text, comment_pubdate=timezone.now(), comment_author = request.user)
            new_comment.save()
            return HttpResponseRedirect(reverse('forum:post', args=post_id))
    else:
        comment_form = CreateComment()
        template = loader.get_template('forum/post.html')
        post = get_object_or_404(Post, pk=post_id)
        comments = Comment.objects.filter(comment_post_id=post_id).order_by('-comment_pubdate')[:10]
        context={
            'post':post,
            'comments':comments,
            'comment_form':comment_form
        }
        return HttpResponse(template.render(context,request))

# def comment(request, post_id):
#     if request.method == 'POST':
#         newcomment =
#     return HttpResponseRedirect(reverse('forum:post', args=post_id))

def createPost(request):
    if request.method == 'POST':
        post_form = CreatePost(request.POST)
        if post_form.is_valid():
            new_post_title = post_form.cleaned_data['title']
            new_post_text = post_form.cleaned_data['content']
            new_post = Post(post_title = new_post_title, post_text = new_post_text, post_author = request.user, post_pubdate = timezone.now())
            new_post.save()
            return HttpResponseRedirect(reverse('forum:index'))
    else:
        post_form = CreatePost()
        template = loader.get_template('forum/create.html')
        context = {
            'post_form':post_form
        }
        return HttpResponse(template.render(context,request))

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as django_logout
from django.contrib.auth.forms import  UserCreationForm

# Create your views here.
def index(request):
    return render(request,'home/home.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password=raw_password)
            login(request, user)
    else:
        form = UserCreationForm()
    return render(request,'home/signup.html',{'form':form})


def logout(request):
    django_logout(request)
    return HttpResponseRedirect('/home')

forum/templates/forum/create.html
{% extends 'home/base.html' %}

{% block content %}

    <h3>Create your post</h3>
    <form action="{% url 'forum:createPost' %}" method="post">
        {% csrf_token %}
        {{post_form.as_p}}
        <button type='Submit'/>Create</button>
    </form>
    <a href="{% url 'forum:index' %}">Back to forum</a>

{% endblock %}

forum/templates/forum/forum.html
{% extends 'home/base.html' %}

{% block content %}
    <a href="{% url 'forum:createPost' %}">Create a post</a>
    {% if latest_post_list %}
        <ul>
            {% for post in latest_post_list %}
                <li><a href="{% url 'forum:post' post.id %}">{{post.post_title}}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts here :(</p>
    {% endif %}
{% endblock %}

forum/templates/forum/post.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>{{post.post_title}}</h1>

    <p>{{post.post_text}}</p>

    <a href="{% url 'forum:index' %}">Back to forum</a>

    {% if user.is_authenticated %}
        <form action="{% url 'forum:post' post.id %}" method ="post">
            {%csrf_token%}
            {{comment_form}}
        </form>
    {% else %}
        <p><a href="{% url 'home:login' %}">Log-in</a> or <a href="{% url 'home:signup'%}">Create an account</a> to comment</p>
    {% endif %}

    {% for comment in comments %}
        <h6>{{comment.comment_text}}</h6> <p>-{{comment.comment_author}}</p>
    {% endfor %}
{% endblock %}

home/templates/home/base.html
<!DOCTYPE HTML>

<head>
    <title>Hi!</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type = "text/css"/>
    <meta name="viewport" content = "width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-10">
                <h1>Forum</h1>
            </div>
            {% if user.is_authenticated %}
                <div class="col-auto">
                    <p>{{user.username}} is logged in!</p>
                </div>
                <div class="col">
                    <a href="{%url 'logout'%}">Logout</a>
                </div>
            {% else %}
                <div class="col">
                    <a href= "/home/login">Log-in</a>
                </div>
                <div class="col">
                    <a href = "/home/signup">Sign-up</a>
                </div>
            {% endif %}
        </div>
    </div>

    {% block content %}

    {% endblock %}
</body>

home/templates/home/home.html
{% extends "home/base.html" %}

{% block content %}
    <a href="{% url 'forum:index' %}">Go to forums</a>



{% endblock %}

home/templates/home/login.html
{% extends "home/base.html"%}

{% block content %}
    <form name="login">
        <p>Username:</p><input type="text" name="username"/>
        <p>Password:</p><input type="text" name="password"/>
        <br >
        <br >
        <button type="submit">Log-in</button>
    </form>
{% endblock %}

home/templates/home/logout.html
{% extends "home/base.html"%}

{% block content %}
    <h2>Logged out!</h2>
    <a href=''>Back</a>
{% endblock %}

home/templates/home/signup.html
{% extends "home/base.html" %}

{% block content %}
    <p>Sign-up Here!</p>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Sign-up</button>
    </form>
{% endblock %}